
const DATA=window.PORTAL_DATA||{books:[],resources:[]};
const books=DATA.books||[], resources=DATA.resources||[];
const grades=['01 ශ්‍රේණිය','02 ශ්‍රේණිය','03 ශ්‍රේණිය','04 ශ්‍රේණිය','05 ශ්‍රේණිය','06 ශ්‍රේණිය','07 ශ්‍රේණිය','08 ශ්‍රේණිය','09 ශ්‍රේණිය','10 ශ්‍රේණිය','11 ශ්‍රේණිය','11 ධර්මාචාර්ය','12 ධර්මාචාර්ය'];
const terms=['පළමු වාරය','දෙවන වාරය','තෙවන වාරය'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');
document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>document.getElementById('nav').classList.remove('open'));
document.getElementById('bookCount').textContent=books.length;
const cats=[...new Set(books.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'si'));
document.getElementById('catCount').textContent=cats.length;
const gradeGrid=document.getElementById('gradeGrid'),panel=document.getElementById('academyPanel'),gradeTitle=document.getElementById('gradeTitle'),gradeMeta=document.getElementById('gradeMeta'),termTabs=document.getElementById('termTabs'),resourceGrid=document.getElementById('resourceGrid');
let selectedGrade='',selectedTerm='පළමු වාරය';
gradeGrid.innerHTML=grades.map((g,i)=>`<button class="grade-card" data-grade="${g}"><i>${i<9?i+1+'️⃣':i<11?'📘':'🎓'}</i><b>${g}</b><small>තෝරාගත් සම්පත්</small></button>`).join('');
function renderTerms(){termTabs.innerHTML=terms.map(t=>`<button class="tab ${t===selectedTerm?'active':''}" data-term="${t}">${t}</button>`).join('');termTabs.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{selectedTerm=b.dataset.term;renderTerms();renderResources();});}
function typeName(t){return {note:'වැදගත් සටහන්',paper:'ප්‍රශ්න පත්‍ර',quiz:'MCQ',video:'වීඩියෝ',form:'Google Form'}[t]||'අධ්‍යයන සම්පත'}
function renderResources(){let list=resources.filter(r=>r.grade===selectedGrade&&(!r.term||r.term===selectedTerm));if(!list.length)list=[{id:'COMING',title:`${selectedGrade} – ${selectedTerm}`,subject:'තෝරාගත් සම්පත්',resourceType:'note',description:'මෙම කොටසට වැදගත් සටහන්, වීඩියෝ, MCQ, Google Form සහ ප්‍රශ්න පත්‍ර පසුව එක් කළ හැක.'}];resourceGrid.innerHTML=list.map(r=>`<article class="resource-card"><span>📘</span><h4>${esc(r.title)}</h4><p>${esc(r.description)}</p><div class="chips"><span class="chip">${esc(typeName(r.resourceType))}</span><span class="chip">${esc(r.subject||'')}</span></div><br><button class="open-resource" data-id="${esc(r.id)}">විස්තර බලන්න</button></article>`).join('');resourceGrid.querySelectorAll('.open-resource').forEach(b=>b.onclick=()=>openResource(b.dataset.id,list));}
gradeGrid.querySelectorAll('.grade-card').forEach(c=>c.onclick=()=>{gradeGrid.querySelectorAll('.grade-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');selectedGrade=c.dataset.grade;selectedTerm='පළමු වාරය';gradeTitle.textContent=selectedGrade;gradeMeta.textContent='SASUNA DHAMMA ACADEMY';panel.classList.remove('hidden');renderTerms();renderResources();panel.scrollIntoView({behavior:'smooth',block:'start'});});
document.getElementById('closePanel').onclick=()=>panel.classList.add('hidden');
const modal=document.getElementById('modal'),modalBody=document.getElementById('modalBody');document.getElementById('modalClose').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
function openResource(id,list){const r=list.find(x=>x.id===id)||list[0];modalBody.innerHTML=`<span class="eyebrow">${esc(selectedGrade)} • ${esc(selectedTerm)}</span><h2>${esc(r.title)}</h2><p>${esc(r.description)}</p><h3>මෙම පාඩමේ අංග</h3><div class="modal-actions">${r.video?`<a href="${esc(r.video)}" target="_blank">🎥 වීඩියෝ</a>`:'<a href="#" onclick="return false">🎥 වීඩියෝ ළඟදීම</a>'}${r.form?`<a href="${esc(r.form)}" target="_blank">✍️ Google Form</a>`:'<a href="#" onclick="return false">✍️ Google Form ළඟදීම</a>'}${r.pdf?`<a href="${esc(r.pdf)}" target="_blank">📄 PDF</a>`:'<a href="#" onclick="return false">📄 PDF ළඟදීම</a>'}<a href="#" onclick="return false">❓ MCQ Demo</a></div>`;modal.classList.remove('hidden');}
const search=document.getElementById('bookSearch'),cat=document.getElementById('categoryFilter'),shelf=document.getElementById('shelfFilter'),bookGrid=document.getElementById('bookGrid'),result=document.getElementById('resultCount'),more=document.getElementById('moreBtn');let visible=18;
[...new Set(books.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'si')).forEach(v=>cat.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));[...new Set(books.map(x=>x.shelf).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'si')).forEach(v=>shelf.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));
function filtered(){const q=search.value.trim().toLocaleLowerCase('si');return books.filter(b=>{const hay=`${b.id} ${b.title} ${b.author} ${b.category} ${b.shelf}`.toLocaleLowerCase('si');return (!q||hay.includes(q))&&(!cat.value||b.category===cat.value)&&(!shelf.value||b.shelf===shelf.value);});}
function renderBooks(reset=false){if(reset)visible=18;const list=filtered();result.textContent=`ප්‍රතිඵල ${list.length}ක්`;bookGrid.innerHTML=list.slice(0,visible).map(b=>`<article class="book-card" data-id="${esc(b.id)}"><div class="book-top"><span>📘</span><span class="book-id">${esc(b.id)}</span></div><h3>${esc(b.title)}</h3><p class="meta"><b>කර්තෘ:</b> ${esc(b.author||'—')}</p><p class="meta"><b>විෂය:</b> ${esc(b.category||'—')}</p><span class="available">✓ පුස්තකාලයේ ඇත</span></article>`).join('')||'<div class="empty">පොතක් හමු නොවීය.</div>';more.style.display=visible<list.length?'block':'none';bookGrid.querySelectorAll('.book-card').forEach(c=>c.onclick=()=>openBook(c.dataset.id));}
function openBook(id){const b=books.find(x=>x.id===id);if(!b)return;modalBody.innerHTML=`<span class="eyebrow">${esc(b.id)}</span><h2>${esc(b.title)}</h2><p><b>කර්තෘ:</b> ${esc(b.author||'—')}</p><p><b>විෂය:</b> ${esc(b.category||'—')}</p><p><b>රාක්කය:</b> ${esc(b.shelf||'—')}</p><p><b>තත්ත්වය:</b> පුස්තකාලයේ ඇත</p>`;modal.classList.remove('hidden');}
[search,cat,shelf].forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',()=>renderBooks(true)));more.onclick=()=>{visible+=18;renderBooks()};document.getElementById('resetBtn').onclick=()=>{search.value='';cat.value='';shelf.value='';renderBooks(true)};renderBooks();
